# Usa una imagen base oficial de Python
FROM python:3.9-slim

# Establece el directorio de trabajo
WORKDIR /app

# Copia los archivos de tu aplicación
COPY . /app

# Instala las dependencias
RUN pip install -r requirements.txt

# Expone el puerto que usará la aplicación
EXPOSE 8080

# Comando para ejecutar tu aplicación
CMD ["python", "ApiGetUrl.py"]
